CREATE TABLE `solicitacoes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome_solicitacao` varchar(255) NOT NULL,
	`projeto` varchar(255),
	`servico` varchar(255),
	`operadora` varchar(255),
	`freshdesk_ticket` varchar(100),
	`rua` varchar(255),
	`numero` varchar(10),
	`complemento` varchar(255),
	`bairro` varchar(255),
	`cidade` varchar(255),
	`uf` varchar(2),
	`contato_local` varchar(255),
	`data_atividade` date,
	`hora_atividade` time,
	`status` enum('pendente','em_progresso','concluida','cancelada') DEFAULT 'pendente',
	`data_conclusao` date,
	`horario_chegada` time,
	`horario_liberacao` time,
	`horario_termino` time,
	`total_horas` decimal(5,2),
	`faturamento` decimal(10,2),
	`observacoes` text,
	`tecnico_id` int,
	`criado_por` int,
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `solicitacoes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tecnicos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nome` varchar(255) NOT NULL,
	`telefone` varchar(20),
	`cpf` varchar(14),
	`rg` varchar(20),
	`cep` varchar(10),
	`rua` varchar(255),
	`numero` varchar(10),
	`complemento` varchar(255),
	`bairro` varchar(255),
	`cidade` varchar(255),
	`uf` varchar(2),
	`empresa_parceira` varchar(255),
	`equipamentos` text,
	`avaliacao` decimal(3,2),
	`latitude` decimal(10,8),
	`longitude` decimal(11,8),
	`ativo` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tecnicos_id` PRIMARY KEY(`id`),
	CONSTRAINT `tecnicos_cpf_unique` UNIQUE(`cpf`)
);
